name: Build using Cloud Build

on:
  push:
    branches:
    - 'main'

env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  IMAGE_NAME: code-oss-for-slo-generator

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Configure Workload Identity Federation and generate an access token.
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/803140796435/locations/global/workloadIdentityPools/github-identity-pool/providers/github-identity-provider'
        service_account: '${{ secrets.RUN_SA_EMAIL }}'

    # Setup gcloud CLI
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    # Build and push image to Google Container Registry
    - name: Build
      run: |-
        gcloud builds submit \
          --quiet \
          --tag "europe-west9-docker.pkg.dev/$PROJECT_ID/docker/$IMAGE_NAME:$GITHUB_SHA"
